\set ON_ERROR_STOP on
CREATE OR REPLACE AGGREGATE FUNCTION HllCreateSynopsis
AS LANGUAGE 'C++'
NAME 'HllCreateSynopsisFactory'
LIBRARY HllLib;

GRANT EXECUTE ON AGGREGATE FUNCTION HllCreateSynopsis(BIGINT) TO PUBLIC;
